export enum Types{
  GET_ALL_TASK = 'GET_ALL_TASK',
  GET_TASK_DETAIL = 'GET_TASK_DETAIL',
  GET_TASK_ACTIVE = 'GET_TASK_ACTIVE',
  GET_TASK_COMPLETE = 'GET_TASK_COMPLETE',
  ADD_TASK = 'ADD_TASK',
  EDIT_TASK = 'EDIT_TASK',
  DELETE_TASK = 'DELETE_TASK',
  UPDATE_STATUS = 'UPDATE_STATUS',
  CLEAR_MODAL = 'CLEAR_MODAL'
}
